try:
    risky_code()
except:
    pass  # Bad: no specific exception

total = 5 + 3 * 2
print("Risky computation")
